// This file is generated by rust-protobuf 3.5.0. Do not edit
// .proto file is parsed by protoc --rust_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `lotus/exchange/amm_trade.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_5_0;

// @@protoc_insertion_point(message:lotus.exchange.AMMTrade)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct AMMTrade {
    // message fields
    // @@protoc_insertion_point(field:lotus.exchange.AMMTrade.timestamp)
    pub timestamp: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // @@protoc_insertion_point(field:lotus.exchange.AMMTrade.trader_address)
    pub trader_address: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:lotus.exchange.AMMTrade.trade_id)
    pub trade_id: ::std::string::String,
    // @@protoc_insertion_point(field:lotus.exchange.AMMTrade.input_token_address)
    pub input_token_address: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:lotus.exchange.AMMTrade.input_amount)
    pub input_amount: ::std::string::String,
    // @@protoc_insertion_point(field:lotus.exchange.AMMTrade.output_token_address)
    pub output_token_address: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:lotus.exchange.AMMTrade.output_amount)
    pub output_amount: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:lotus.exchange.AMMTrade.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a AMMTrade {
    fn default() -> &'a AMMTrade {
        <AMMTrade as ::protobuf::Message>::default_instance()
    }
}

impl AMMTrade {
    pub fn new() -> AMMTrade {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(7);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "timestamp",
            |m: &AMMTrade| { &m.timestamp },
            |m: &mut AMMTrade| { &mut m.timestamp },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "trader_address",
            |m: &AMMTrade| { &m.trader_address },
            |m: &mut AMMTrade| { &mut m.trader_address },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "trade_id",
            |m: &AMMTrade| { &m.trade_id },
            |m: &mut AMMTrade| { &mut m.trade_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "input_token_address",
            |m: &AMMTrade| { &m.input_token_address },
            |m: &mut AMMTrade| { &mut m.input_token_address },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "input_amount",
            |m: &AMMTrade| { &m.input_amount },
            |m: &mut AMMTrade| { &mut m.input_amount },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "output_token_address",
            |m: &AMMTrade| { &m.output_token_address },
            |m: &mut AMMTrade| { &mut m.output_token_address },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "output_amount",
            |m: &AMMTrade| { &m.output_amount },
            |m: &mut AMMTrade| { &mut m.output_amount },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AMMTrade>(
            "AMMTrade",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for AMMTrade {
    const NAME: &'static str = "AMMTrade";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.timestamp)?;
                },
                18 => {
                    self.trader_address = is.read_bytes()?;
                },
                26 => {
                    self.trade_id = is.read_string()?;
                },
                34 => {
                    self.input_token_address = is.read_bytes()?;
                },
                42 => {
                    self.input_amount = is.read_string()?;
                },
                50 => {
                    self.output_token_address = is.read_bytes()?;
                },
                58 => {
                    self.output_amount = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.timestamp.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if !self.trader_address.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.trader_address);
        }
        if !self.trade_id.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.trade_id);
        }
        if !self.input_token_address.is_empty() {
            my_size += ::protobuf::rt::bytes_size(4, &self.input_token_address);
        }
        if !self.input_amount.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.input_amount);
        }
        if !self.output_token_address.is_empty() {
            my_size += ::protobuf::rt::bytes_size(6, &self.output_token_address);
        }
        if !self.output_amount.is_empty() {
            my_size += ::protobuf::rt::string_size(7, &self.output_amount);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.timestamp.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if !self.trader_address.is_empty() {
            os.write_bytes(2, &self.trader_address)?;
        }
        if !self.trade_id.is_empty() {
            os.write_string(3, &self.trade_id)?;
        }
        if !self.input_token_address.is_empty() {
            os.write_bytes(4, &self.input_token_address)?;
        }
        if !self.input_amount.is_empty() {
            os.write_string(5, &self.input_amount)?;
        }
        if !self.output_token_address.is_empty() {
            os.write_bytes(6, &self.output_token_address)?;
        }
        if !self.output_amount.is_empty() {
            os.write_string(7, &self.output_amount)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> AMMTrade {
        AMMTrade::new()
    }

    fn clear(&mut self) {
        self.timestamp.clear();
        self.trader_address.clear();
        self.trade_id.clear();
        self.input_token_address.clear();
        self.input_amount.clear();
        self.output_token_address.clear();
        self.output_amount.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static AMMTrade {
        static instance: AMMTrade = AMMTrade {
            timestamp: ::protobuf::MessageField::none(),
            trader_address: ::std::vec::Vec::new(),
            trade_id: ::std::string::String::new(),
            input_token_address: ::std::vec::Vec::new(),
            input_amount: ::std::string::String::new(),
            output_token_address: ::std::vec::Vec::new(),
            output_amount: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for AMMTrade {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("AMMTrade").unwrap()).clone()
    }
}

impl ::std::fmt::Display for AMMTrade {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AMMTrade {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1elotus/exchange/amm_trade.proto\x12\x0elotus.exchange\x1a\x1fgoogle\
    /protobuf/timestamp.proto\x1a\x11lotus/lotus.proto\"\xd4\x02\n\x08AMMTra\
    de\x128\n\ttimestamp\x18\x01\x20\x01(\x0b2\x1a.google.protobuf.Timestamp\
    R\ttimestamp\x12-\n\x0etrader_address\x18\x02\x20\x01(\x0cR\rtraderAddre\
    ssB\x06\xd2\xab0\x02\x08\x01\x12\x19\n\x08trade_id\x18\x03\x20\x01(\tR\
    \x07tradeId\x126\n\x13input_token_address\x18\x04\x20\x01(\x0cR\x11input\
    TokenAddressB\x06\xd2\xab0\x02\x08\x01\x12'\n\x0cinput_amount\x18\x05\
    \x20\x01(\tR\x0binputAmountB\x04\xda\xab0\0\x128\n\x14output_token_addre\
    ss\x18\x06\x20\x01(\x0cR\x12outputTokenAddressB\x06\xd2\xab0\x02\x08\x01\
    \x12)\n\routput_amount\x18\x07\x20\x01(\tR\x0coutputAmountB\x04\xda\xab0\
    \0B-Z+github.com/trylotus/go-lotus-proto/exchangeJ\xfe\x04\n\x06\x12\x04\
    \0\0\x11\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x02\
    \0\x17\n\t\n\x02\x03\0\x12\x03\x04\0)\n\t\n\x02\x03\x01\x12\x03\x05\0\
    \x1b\n\x08\n\x01\x08\x12\x03\x07\0B\n\t\n\x02\x08\x0b\x12\x03\x07\0B\n\n\
    \n\x02\x04\0\x12\x04\t\0\x11\x01\n\n\n\x03\x04\0\x01\x12\x03\t\x08\x10\n\
    \x0b\n\x04\x04\0\x02\0\x12\x03\n\x02*\n\x0c\n\x05\x04\0\x02\0\x06\x12\
    \x03\n\x02\x1b\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\n\x1c%\n\x0c\n\x05\
    \x04\0\x02\0\x03\x12\x03\n()\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x0b\x02D\
    \n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x0b\x02\x07\n\x0c\n\x05\x04\0\x02\
    \x01\x01\x12\x03\x0b\x08\x16\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x0b\
    \x19\x1a\n\x0c\n\x05\x04\0\x02\x01\x08\x12\x03\x0b\x1bC\n\x10\n\t\x04\0\
    \x02\x01\x08\xba\x85\x06\x01\x12\x03\x0b\x1cB\n\x0b\n\x04\x04\0\x02\x02\
    \x12\x03\x0c\x02\x16\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x0c\x02\x08\n\
    \x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x0c\t\x11\n\x0c\n\x05\x04\0\x02\x02\
    \x03\x12\x03\x0c\x14\x15\n\x0b\n\x04\x04\0\x02\x03\x12\x03\r\x02I\n\x0c\
    \n\x05\x04\0\x02\x03\x05\x12\x03\r\x02\x07\n\x0c\n\x05\x04\0\x02\x03\x01\
    \x12\x03\r\x08\x1b\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\r\x1e\x1f\n\x0c\
    \n\x05\x04\0\x02\x03\x08\x12\x03\r\x20H\n\x10\n\t\x04\0\x02\x03\x08\xba\
    \x85\x06\x01\x12\x03\r!G\n\x0b\n\x04\x04\0\x02\x04\x12\x03\x0e\x021\n\
    \x0c\n\x05\x04\0\x02\x04\x05\x12\x03\x0e\x02\x08\n\x0c\n\x05\x04\0\x02\
    \x04\x01\x12\x03\x0e\t\x15\n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03\x0e\x18\
    \x19\n\x0c\n\x05\x04\0\x02\x04\x08\x12\x03\x0e\x1a0\n\x0f\n\x08\x04\0\
    \x02\x04\x08\xbb\x85\x06\x12\x03\x0e\x1b/\n\x0b\n\x04\x04\0\x02\x05\x12\
    \x03\x0f\x02J\n\x0c\n\x05\x04\0\x02\x05\x05\x12\x03\x0f\x02\x07\n\x0c\n\
    \x05\x04\0\x02\x05\x01\x12\x03\x0f\x08\x1c\n\x0c\n\x05\x04\0\x02\x05\x03\
    \x12\x03\x0f\x1f\x20\n\x0c\n\x05\x04\0\x02\x05\x08\x12\x03\x0f!I\n\x10\n\
    \t\x04\0\x02\x05\x08\xba\x85\x06\x01\x12\x03\x0f\"H\n\x0b\n\x04\x04\0\
    \x02\x06\x12\x03\x10\x022\n\x0c\n\x05\x04\0\x02\x06\x05\x12\x03\x10\x02\
    \x08\n\x0c\n\x05\x04\0\x02\x06\x01\x12\x03\x10\t\x16\n\x0c\n\x05\x04\0\
    \x02\x06\x03\x12\x03\x10\x19\x1a\n\x0c\n\x05\x04\0\x02\x06\x08\x12\x03\
    \x10\x1b1\n\x0f\n\x08\x04\0\x02\x06\x08\xbb\x85\x06\x12\x03\x10\x1c0b\
    \x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            deps.push(super::lotus::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(AMMTrade::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
