// This file is generated by rust-protobuf 3.5.0. Do not edit
// .proto file is parsed by protoc --rust_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `lotus/evm/erc20.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_5_0;

// @@protoc_insertion_point(message:lotus.evm.ERC20)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ERC20 {
    // message fields
    // @@protoc_insertion_point(field:lotus.evm.ERC20.address)
    pub address: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:lotus.evm.ERC20.name)
    pub name: ::std::string::String,
    // @@protoc_insertion_point(field:lotus.evm.ERC20.symbol)
    pub symbol: ::std::string::String,
    // @@protoc_insertion_point(field:lotus.evm.ERC20.decimals)
    pub decimals: u32,
    // @@protoc_insertion_point(field:lotus.evm.ERC20.total_supply)
    pub total_supply: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:lotus.evm.ERC20.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ERC20 {
    fn default() -> &'a ERC20 {
        <ERC20 as ::protobuf::Message>::default_instance()
    }
}

impl ERC20 {
    pub fn new() -> ERC20 {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "address",
            |m: &ERC20| { &m.address },
            |m: &mut ERC20| { &mut m.address },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &ERC20| { &m.name },
            |m: &mut ERC20| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "symbol",
            |m: &ERC20| { &m.symbol },
            |m: &mut ERC20| { &mut m.symbol },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "decimals",
            |m: &ERC20| { &m.decimals },
            |m: &mut ERC20| { &mut m.decimals },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "total_supply",
            |m: &ERC20| { &m.total_supply },
            |m: &mut ERC20| { &mut m.total_supply },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ERC20>(
            "ERC20",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ERC20 {
    const NAME: &'static str = "ERC20";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.address = is.read_bytes()?;
                },
                18 => {
                    self.name = is.read_string()?;
                },
                26 => {
                    self.symbol = is.read_string()?;
                },
                32 => {
                    self.decimals = is.read_uint32()?;
                },
                42 => {
                    self.total_supply = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.address.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.address);
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.name);
        }
        if !self.symbol.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.symbol);
        }
        if self.decimals != 0 {
            my_size += ::protobuf::rt::uint32_size(4, self.decimals);
        }
        if !self.total_supply.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.total_supply);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.address.is_empty() {
            os.write_bytes(1, &self.address)?;
        }
        if !self.name.is_empty() {
            os.write_string(2, &self.name)?;
        }
        if !self.symbol.is_empty() {
            os.write_string(3, &self.symbol)?;
        }
        if self.decimals != 0 {
            os.write_uint32(4, self.decimals)?;
        }
        if !self.total_supply.is_empty() {
            os.write_string(5, &self.total_supply)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ERC20 {
        ERC20::new()
    }

    fn clear(&mut self) {
        self.address.clear();
        self.name.clear();
        self.symbol.clear();
        self.decimals = 0;
        self.total_supply.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ERC20 {
        static instance: ERC20 = ERC20 {
            address: ::std::vec::Vec::new(),
            name: ::std::string::String::new(),
            symbol: ::std::string::String::new(),
            decimals: 0,
            total_supply: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ERC20 {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ERC20").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ERC20 {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ERC20 {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x15lotus/evm/erc20.proto\x12\tlotus.evm\x1a\x11lotus/lotus.proto\"\
    \x9a\x01\n\x05ERC20\x12\x20\n\x07address\x18\x01\x20\x01(\x0cR\x07addres\
    sB\x06\xd2\xab0\x02\x08\x01\x12\x12\n\x04name\x18\x02\x20\x01(\tR\x04nam\
    e\x12\x16\n\x06symbol\x18\x03\x20\x01(\tR\x06symbol\x12\x1a\n\x08decimal\
    s\x18\x04\x20\x01(\rR\x08decimals\x12'\n\x0ctotal_supply\x18\x05\x20\x01\
    (\tR\x0btotalSupplyB\x04\xda\xab0\0B(Z&github.com/trylotus/go-lotus-prot\
    o/evmJ\xa6\x03\n\x06\x12\x04\0\0\x0e\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\
    \n\x08\n\x01\x02\x12\x03\x02\0\x12\n\t\n\x02\x03\0\x12\x03\x04\0\x1b\n\
    \x08\n\x01\x08\x12\x03\x06\0=\n\t\n\x02\x08\x0b\x12\x03\x06\0=\n\n\n\x02\
    \x04\0\x12\x04\x08\0\x0e\x01\n\n\n\x03\x04\0\x01\x12\x03\x08\x08\r\n\x0b\
    \n\x04\x04\0\x02\0\x12\x03\t\x02=\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\t\
    \x02\x07\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\t\x08\x0f\n\x0c\n\x05\x04\0\
    \x02\0\x03\x12\x03\t\x12\x13\n\x0c\n\x05\x04\0\x02\0\x08\x12\x03\t\x14<\
    \n\x10\n\t\x04\0\x02\0\x08\xba\x85\x06\x01\x12\x03\t\x15;\n\x0b\n\x04\
    \x04\0\x02\x01\x12\x03\n\x02\x12\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\n\
    \x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\n\t\r\n\x0c\n\x05\x04\0\
    \x02\x01\x03\x12\x03\n\x10\x11\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x0b\x02\
    \x14\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x0b\x02\x08\n\x0c\n\x05\x04\0\
    \x02\x02\x01\x12\x03\x0b\t\x0f\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x0b\
    \x12\x13\n\x0b\n\x04\x04\0\x02\x03\x12\x03\x0c\x02\x16\n\x0c\n\x05\x04\0\
    \x02\x03\x05\x12\x03\x0c\x02\x08\n\x0c\n\x05\x04\0\x02\x03\x01\x12\x03\
    \x0c\t\x11\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\x0c\x14\x15\n\x0b\n\x04\
    \x04\0\x02\x04\x12\x03\r\x021\n\x0c\n\x05\x04\0\x02\x04\x05\x12\x03\r\
    \x02\x08\n\x0c\n\x05\x04\0\x02\x04\x01\x12\x03\r\t\x15\n\x0c\n\x05\x04\0\
    \x02\x04\x03\x12\x03\r\x18\x19\n\x0c\n\x05\x04\0\x02\x04\x08\x12\x03\r\
    \x1a0\n\x0f\n\x08\x04\0\x02\x04\x08\xbb\x85\x06\x12\x03\r\x1b/b\x06proto\
    3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::lotus::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(ERC20::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
