// This file is generated by rust-protobuf 3.5.0. Do not edit
// .proto file is parsed by protoc --rust_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `lotus/staking/validator.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_5_0;

// @@protoc_insertion_point(message:lotus.staking.Validator)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Validator {
    // message fields
    // @@protoc_insertion_point(field:lotus.staking.Validator.validator_address)
    pub validator_address: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:lotus.staking.Validator.total_stake)
    pub total_stake: ::std::string::String,
    // @@protoc_insertion_point(field:lotus.staking.Validator.commission_rate)
    pub commission_rate: ::std::string::String,
    // @@protoc_insertion_point(field:lotus.staking.Validator.is_active)
    pub is_active: bool,
    // special fields
    // @@protoc_insertion_point(special_field:lotus.staking.Validator.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Validator {
    fn default() -> &'a Validator {
        <Validator as ::protobuf::Message>::default_instance()
    }
}

impl Validator {
    pub fn new() -> Validator {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "validator_address",
            |m: &Validator| { &m.validator_address },
            |m: &mut Validator| { &mut m.validator_address },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "total_stake",
            |m: &Validator| { &m.total_stake },
            |m: &mut Validator| { &mut m.total_stake },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "commission_rate",
            |m: &Validator| { &m.commission_rate },
            |m: &mut Validator| { &mut m.commission_rate },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "is_active",
            |m: &Validator| { &m.is_active },
            |m: &mut Validator| { &mut m.is_active },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Validator>(
            "Validator",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Validator {
    const NAME: &'static str = "Validator";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.validator_address = is.read_bytes()?;
                },
                18 => {
                    self.total_stake = is.read_string()?;
                },
                26 => {
                    self.commission_rate = is.read_string()?;
                },
                32 => {
                    self.is_active = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.validator_address.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.validator_address);
        }
        if !self.total_stake.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.total_stake);
        }
        if !self.commission_rate.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.commission_rate);
        }
        if self.is_active != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.validator_address.is_empty() {
            os.write_bytes(1, &self.validator_address)?;
        }
        if !self.total_stake.is_empty() {
            os.write_string(2, &self.total_stake)?;
        }
        if !self.commission_rate.is_empty() {
            os.write_string(3, &self.commission_rate)?;
        }
        if self.is_active != false {
            os.write_bool(4, self.is_active)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Validator {
        Validator::new()
    }

    fn clear(&mut self) {
        self.validator_address.clear();
        self.total_stake.clear();
        self.commission_rate.clear();
        self.is_active = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Validator {
        static instance: Validator = Validator {
            validator_address: ::std::vec::Vec::new(),
            total_stake: ::std::string::String::new(),
            commission_rate: ::std::string::String::new(),
            is_active: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Validator {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Validator").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Validator {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Validator {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1dlotus/staking/validator.proto\x12\rlotus.staking\x1a\x11lotus/lotu\
    s.proto\"\xb3\x01\n\tValidator\x123\n\x11validator_address\x18\x01\x20\
    \x01(\x0cR\x10validatorAddressB\x06\xd2\xab0\x02\x08\x01\x12%\n\x0btotal\
    _stake\x18\x02\x20\x01(\tR\ntotalStakeB\x04\xda\xab0\0\x12-\n\x0fcommiss\
    ion_rate\x18\x03\x20\x01(\tR\x0ecommissionRateB\x04\xda\xab0\0\x12\x1b\n\
    \tis_active\x18\x04\x20\x01(\x08R\x08isActiveB,Z*github.com/trylotus/go-\
    lotus-proto/stakingJ\x8e\x03\n\x06\x12\x04\0\0\r\x01\n\x08\n\x01\x0c\x12\
    \x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x02\0\x16\n\t\n\x02\x03\0\x12\x03\
    \x04\0\x1b\n\x08\n\x01\x08\x12\x03\x06\0A\n\t\n\x02\x08\x0b\x12\x03\x06\
    \0A\n\n\n\x02\x04\0\x12\x04\x08\0\r\x01\n\n\n\x03\x04\0\x01\x12\x03\x08\
    \x08\x11\n\x0b\n\x04\x04\0\x02\0\x12\x03\t\x02G\n\x0c\n\x05\x04\0\x02\0\
    \x05\x12\x03\t\x02\x07\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\t\x08\x19\n\
    \x0c\n\x05\x04\0\x02\0\x03\x12\x03\t\x1c\x1d\n\x0c\n\x05\x04\0\x02\0\x08\
    \x12\x03\t\x1eF\n\x10\n\t\x04\0\x02\0\x08\xba\x85\x06\x01\x12\x03\t\x1fE\
    \n\x0b\n\x04\x04\0\x02\x01\x12\x03\n\x020\n\x0c\n\x05\x04\0\x02\x01\x05\
    \x12\x03\n\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\n\t\x14\n\x0c\n\
    \x05\x04\0\x02\x01\x03\x12\x03\n\x17\x18\n\x0c\n\x05\x04\0\x02\x01\x08\
    \x12\x03\n\x19/\n\x0f\n\x08\x04\0\x02\x01\x08\xbb\x85\x06\x12\x03\n\x1a.\
    \n\x0b\n\x04\x04\0\x02\x02\x12\x03\x0b\x024\n\x0c\n\x05\x04\0\x02\x02\
    \x05\x12\x03\x0b\x02\x08\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x0b\t\x18\
    \n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x0b\x1b\x1c\n\x0c\n\x05\x04\0\x02\
    \x02\x08\x12\x03\x0b\x1d3\n\x0f\n\x08\x04\0\x02\x02\x08\xbb\x85\x06\x12\
    \x03\x0b\x1e2\n\x0b\n\x04\x04\0\x02\x03\x12\x03\x0c\x02\x15\n\x0c\n\x05\
    \x04\0\x02\x03\x05\x12\x03\x0c\x02\x06\n\x0c\n\x05\x04\0\x02\x03\x01\x12\
    \x03\x0c\x07\x10\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\x0c\x13\x14b\x06p\
    roto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::lotus::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(Validator::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
