// This file is generated by rust-protobuf 3.5.0. Do not edit
// .proto file is parsed by protoc --rust_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `lotus/lotus.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_5_0;

///  Defines options for indexing a field.
// @@protoc_insertion_point(message:lotus.IndexOption)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct IndexOption {
    // message fields
    ///  Type of index (defaults to ordered).
    // @@protoc_insertion_point(field:lotus.IndexOption.type)
    pub type_: ::protobuf::EnumOrUnknown<IndexType>,
    ///  Whether this is a unique index (defaults to false).
    // @@protoc_insertion_point(field:lotus.IndexOption.unique)
    pub unique: bool,
    // special fields
    // @@protoc_insertion_point(special_field:lotus.IndexOption.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a IndexOption {
    fn default() -> &'a IndexOption {
        <IndexOption as ::protobuf::Message>::default_instance()
    }
}

impl IndexOption {
    pub fn new() -> IndexOption {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "type",
            |m: &IndexOption| { &m.type_ },
            |m: &mut IndexOption| { &mut m.type_ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "unique",
            |m: &IndexOption| { &m.unique },
            |m: &mut IndexOption| { &mut m.unique },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<IndexOption>(
            "IndexOption",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for IndexOption {
    const NAME: &'static str = "IndexOption";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.type_ = is.read_enum_or_unknown()?;
                },
                16 => {
                    self.unique = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.type_ != ::protobuf::EnumOrUnknown::new(IndexType::INDEX_TYPE_ORDERED) {
            my_size += ::protobuf::rt::int32_size(1, self.type_.value());
        }
        if self.unique != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.type_ != ::protobuf::EnumOrUnknown::new(IndexType::INDEX_TYPE_ORDERED) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.type_))?;
        }
        if self.unique != false {
            os.write_bool(2, self.unique)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> IndexOption {
        IndexOption::new()
    }

    fn clear(&mut self) {
        self.type_ = ::protobuf::EnumOrUnknown::new(IndexType::INDEX_TYPE_ORDERED);
        self.unique = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static IndexOption {
        static instance: IndexOption = IndexOption {
            type_: ::protobuf::EnumOrUnknown::from_i32(0),
            unique: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for IndexOption {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("IndexOption").unwrap()).clone()
    }
}

impl ::std::fmt::Display for IndexOption {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for IndexOption {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Defines options for indexing multiple fields.
// @@protoc_insertion_point(message:lotus.CompositeIndexesOption)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CompositeIndexesOption {
    // message fields
    ///  List of composite indexes.
    // @@protoc_insertion_point(field:lotus.CompositeIndexesOption.index)
    pub index: ::std::vec::Vec<CompositeIndexOption>,
    // special fields
    // @@protoc_insertion_point(special_field:lotus.CompositeIndexesOption.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CompositeIndexesOption {
    fn default() -> &'a CompositeIndexesOption {
        <CompositeIndexesOption as ::protobuf::Message>::default_instance()
    }
}

impl CompositeIndexesOption {
    pub fn new() -> CompositeIndexesOption {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "index",
            |m: &CompositeIndexesOption| { &m.index },
            |m: &mut CompositeIndexesOption| { &mut m.index },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CompositeIndexesOption>(
            "CompositeIndexesOption",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CompositeIndexesOption {
    const NAME: &'static str = "CompositeIndexesOption";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.index.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.index {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.index {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CompositeIndexesOption {
        CompositeIndexesOption::new()
    }

    fn clear(&mut self) {
        self.index.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CompositeIndexesOption {
        static instance: CompositeIndexesOption = CompositeIndexesOption {
            index: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CompositeIndexesOption {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CompositeIndexesOption").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CompositeIndexesOption {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CompositeIndexesOption {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Defines options for composite indexes involving multiple fields.
// @@protoc_insertion_point(message:lotus.CompositeIndexOption)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CompositeIndexOption {
    // message fields
    ///  Type of composite index (defaults to ordered).
    // @@protoc_insertion_point(field:lotus.CompositeIndexOption.type)
    pub type_: ::protobuf::EnumOrUnknown<IndexType>,
    ///  Whether this is a unique index (defaults to false).
    // @@protoc_insertion_point(field:lotus.CompositeIndexOption.unique)
    pub unique: bool,
    ///  List of field names involved in the composite index.
    // @@protoc_insertion_point(field:lotus.CompositeIndexOption.fields)
    pub fields: ::std::vec::Vec<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:lotus.CompositeIndexOption.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CompositeIndexOption {
    fn default() -> &'a CompositeIndexOption {
        <CompositeIndexOption as ::protobuf::Message>::default_instance()
    }
}

impl CompositeIndexOption {
    pub fn new() -> CompositeIndexOption {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "type",
            |m: &CompositeIndexOption| { &m.type_ },
            |m: &mut CompositeIndexOption| { &mut m.type_ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "unique",
            |m: &CompositeIndexOption| { &m.unique },
            |m: &mut CompositeIndexOption| { &mut m.unique },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "fields",
            |m: &CompositeIndexOption| { &m.fields },
            |m: &mut CompositeIndexOption| { &mut m.fields },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CompositeIndexOption>(
            "CompositeIndexOption",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CompositeIndexOption {
    const NAME: &'static str = "CompositeIndexOption";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.type_ = is.read_enum_or_unknown()?;
                },
                16 => {
                    self.unique = is.read_bool()?;
                },
                26 => {
                    self.fields.push(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.type_ != ::protobuf::EnumOrUnknown::new(IndexType::INDEX_TYPE_ORDERED) {
            my_size += ::protobuf::rt::int32_size(1, self.type_.value());
        }
        if self.unique != false {
            my_size += 1 + 1;
        }
        for value in &self.fields {
            my_size += ::protobuf::rt::string_size(3, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.type_ != ::protobuf::EnumOrUnknown::new(IndexType::INDEX_TYPE_ORDERED) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.type_))?;
        }
        if self.unique != false {
            os.write_bool(2, self.unique)?;
        }
        for v in &self.fields {
            os.write_string(3, &v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CompositeIndexOption {
        CompositeIndexOption::new()
    }

    fn clear(&mut self) {
        self.type_ = ::protobuf::EnumOrUnknown::new(IndexType::INDEX_TYPE_ORDERED);
        self.unique = false;
        self.fields.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CompositeIndexOption {
        static instance: CompositeIndexOption = CompositeIndexOption {
            type_: ::protobuf::EnumOrUnknown::from_i32(0),
            unique: false,
            fields: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CompositeIndexOption {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CompositeIndexOption").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CompositeIndexOption {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CompositeIndexOption {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Defines options for how bytes fields are encoded/decoded.
// @@protoc_insertion_point(message:lotus.BytesOption)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct BytesOption {
    // message fields
    ///  Format to use for displaying binary data (defaults to base64).
    // @@protoc_insertion_point(field:lotus.BytesOption.format)
    pub format: ::protobuf::EnumOrUnknown<FormatType>,
    // special fields
    // @@protoc_insertion_point(special_field:lotus.BytesOption.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a BytesOption {
    fn default() -> &'a BytesOption {
        <BytesOption as ::protobuf::Message>::default_instance()
    }
}

impl BytesOption {
    pub fn new() -> BytesOption {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "format",
            |m: &BytesOption| { &m.format },
            |m: &mut BytesOption| { &mut m.format },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<BytesOption>(
            "BytesOption",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for BytesOption {
    const NAME: &'static str = "BytesOption";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.format = is.read_enum_or_unknown()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.format != ::protobuf::EnumOrUnknown::new(FormatType::FORMAT_TYPE_BASE64) {
            my_size += ::protobuf::rt::int32_size(1, self.format.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.format != ::protobuf::EnumOrUnknown::new(FormatType::FORMAT_TYPE_BASE64) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.format))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> BytesOption {
        BytesOption::new()
    }

    fn clear(&mut self) {
        self.format = ::protobuf::EnumOrUnknown::new(FormatType::FORMAT_TYPE_BASE64);
        self.special_fields.clear();
    }

    fn default_instance() -> &'static BytesOption {
        static instance: BytesOption = BytesOption {
            format: ::protobuf::EnumOrUnknown::from_i32(0),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for BytesOption {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("BytesOption").unwrap()).clone()
    }
}

impl ::std::fmt::Display for BytesOption {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BytesOption {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Defines options for how numeric fields are scaled/represented.
// @@protoc_insertion_point(message:lotus.NumericOption)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct NumericOption {
    // message fields
    ///  Total number of significant digits (including decimals).
    // @@protoc_insertion_point(field:lotus.NumericOption.precision)
    pub precision: ::std::option::Option<u32>,
    ///  Number of decimal places (0 for integers).
    // @@protoc_insertion_point(field:lotus.NumericOption.scale)
    pub scale: ::std::option::Option<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:lotus.NumericOption.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a NumericOption {
    fn default() -> &'a NumericOption {
        <NumericOption as ::protobuf::Message>::default_instance()
    }
}

impl NumericOption {
    pub fn new() -> NumericOption {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "precision",
            |m: &NumericOption| { &m.precision },
            |m: &mut NumericOption| { &mut m.precision },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "scale",
            |m: &NumericOption| { &m.scale },
            |m: &mut NumericOption| { &mut m.scale },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<NumericOption>(
            "NumericOption",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for NumericOption {
    const NAME: &'static str = "NumericOption";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.precision = ::std::option::Option::Some(is.read_uint32()?);
                },
                16 => {
                    self.scale = ::std::option::Option::Some(is.read_uint32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.precision {
            my_size += ::protobuf::rt::uint32_size(1, v);
        }
        if let Some(v) = self.scale {
            my_size += ::protobuf::rt::uint32_size(2, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.precision {
            os.write_uint32(1, v)?;
        }
        if let Some(v) = self.scale {
            os.write_uint32(2, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> NumericOption {
        NumericOption::new()
    }

    fn clear(&mut self) {
        self.precision = ::std::option::Option::None;
        self.scale = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static NumericOption {
        static instance: NumericOption = NumericOption {
            precision: ::std::option::Option::None,
            scale: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for NumericOption {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("NumericOption").unwrap()).clone()
    }
}

impl ::std::fmt::Display for NumericOption {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NumericOption {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Specifies the type of index.
#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:lotus.IndexType)
pub enum IndexType {
    // @@protoc_insertion_point(enum_value:lotus.IndexType.INDEX_TYPE_ORDERED)
    INDEX_TYPE_ORDERED = 0,
    // @@protoc_insertion_point(enum_value:lotus.IndexType.INDEX_TYPE_UNORDERED)
    INDEX_TYPE_UNORDERED = 1,
}

impl ::protobuf::Enum for IndexType {
    const NAME: &'static str = "IndexType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<IndexType> {
        match value {
            0 => ::std::option::Option::Some(IndexType::INDEX_TYPE_ORDERED),
            1 => ::std::option::Option::Some(IndexType::INDEX_TYPE_UNORDERED),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<IndexType> {
        match str {
            "INDEX_TYPE_ORDERED" => ::std::option::Option::Some(IndexType::INDEX_TYPE_ORDERED),
            "INDEX_TYPE_UNORDERED" => ::std::option::Option::Some(IndexType::INDEX_TYPE_UNORDERED),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [IndexType] = &[
        IndexType::INDEX_TYPE_ORDERED,
        IndexType::INDEX_TYPE_UNORDERED,
    ];
}

impl ::protobuf::EnumFull for IndexType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("IndexType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for IndexType {
    fn default() -> Self {
        IndexType::INDEX_TYPE_ORDERED
    }
}

impl IndexType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<IndexType>("IndexType")
    }
}

///  Specifies the format for encoding/decoding bytes data.
#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:lotus.FormatType)
pub enum FormatType {
    // @@protoc_insertion_point(enum_value:lotus.FormatType.FORMAT_TYPE_BASE64)
    FORMAT_TYPE_BASE64 = 0,
    // @@protoc_insertion_point(enum_value:lotus.FormatType.FORMAT_TYPE_HEX)
    FORMAT_TYPE_HEX = 1,
}

impl ::protobuf::Enum for FormatType {
    const NAME: &'static str = "FormatType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<FormatType> {
        match value {
            0 => ::std::option::Option::Some(FormatType::FORMAT_TYPE_BASE64),
            1 => ::std::option::Option::Some(FormatType::FORMAT_TYPE_HEX),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<FormatType> {
        match str {
            "FORMAT_TYPE_BASE64" => ::std::option::Option::Some(FormatType::FORMAT_TYPE_BASE64),
            "FORMAT_TYPE_HEX" => ::std::option::Option::Some(FormatType::FORMAT_TYPE_HEX),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [FormatType] = &[
        FormatType::FORMAT_TYPE_BASE64,
        FormatType::FORMAT_TYPE_HEX,
    ];
}

impl ::protobuf::EnumFull for FormatType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("FormatType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for FormatType {
    fn default() -> Self {
        FormatType::FORMAT_TYPE_BASE64
    }
}

impl FormatType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<FormatType>("FormatType")
    }
}

/// Extension fields
pub mod exts {

    pub const composite: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, super::CompositeIndexesOption> = ::protobuf::ext::ExtFieldOptional::new(99001, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_MESSAGE);

    pub const index: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, super::IndexOption> = ::protobuf::ext::ExtFieldOptional::new(99001, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_MESSAGE);

    pub const bytes: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, super::BytesOption> = ::protobuf::ext::ExtFieldOptional::new(99002, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_MESSAGE);

    pub const numeric: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, super::NumericOption> = ::protobuf::ext::ExtFieldOptional::new(99003, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_MESSAGE);
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11lotus/lotus.proto\x12\x05lotus\x1a\x20google/protobuf/descriptor.p\
    roto\"K\n\x0bIndexOption\x12$\n\x04type\x18\x01\x20\x01(\x0e2\x10.lotus.\
    IndexTypeR\x04type\x12\x16\n\x06unique\x18\x02\x20\x01(\x08R\x06unique\"\
    K\n\x16CompositeIndexesOption\x121\n\x05index\x18\x01\x20\x03(\x0b2\x1b.\
    lotus.CompositeIndexOptionR\x05index\"l\n\x14CompositeIndexOption\x12$\n\
    \x04type\x18\x01\x20\x01(\x0e2\x10.lotus.IndexTypeR\x04type\x12\x16\n\
    \x06unique\x18\x02\x20\x01(\x08R\x06unique\x12\x16\n\x06fields\x18\x03\
    \x20\x03(\tR\x06fields\"8\n\x0bBytesOption\x12)\n\x06format\x18\x01\x20\
    \x01(\x0e2\x11.lotus.FormatTypeR\x06format\"e\n\rNumericOption\x12!\n\tp\
    recision\x18\x01\x20\x01(\rH\0R\tprecision\x88\x01\x01\x12\x19\n\x05scal\
    e\x18\x02\x20\x01(\rH\x01R\x05scale\x88\x01\x01B\x0c\n\n_precisionB\x08\
    \n\x06_scale*=\n\tIndexType\x12\x16\n\x12INDEX_TYPE_ORDERED\x10\0\x12\
    \x18\n\x14INDEX_TYPE_UNORDERED\x10\x01*9\n\nFormatType\x12\x16\n\x12FORM\
    AT_TYPE_BASE64\x10\0\x12\x13\n\x0fFORMAT_TYPE_HEX\x10\x01:a\n\tcomposite\
    \x18\xb9\x85\x06\x20\x01(\x0b2\x1d.lotus.CompositeIndexesOption\x12\x1f.\
    google.protobuf.MessageOptionsR\tcomposite\x88\x01\x01:L\n\x05index\x18\
    \xb9\x85\x06\x20\x01(\x0b2\x12.lotus.IndexOption\x12\x1d.google.protobuf\
    .FieldOptionsR\x05index\x88\x01\x01:L\n\x05bytes\x18\xba\x85\x06\x20\x01\
    (\x0b2\x12.lotus.BytesOption\x12\x1d.google.protobuf.FieldOptionsR\x05by\
    tes\x88\x01\x01:R\n\x07numeric\x18\xbb\x85\x06\x20\x01(\x0b2\x14.lotus.N\
    umericOption\x12\x1d.google.protobuf.FieldOptionsR\x07numeric\x88\x01\
    \x01B*Z(github.com/trylotus/go-lotus-proto;lotusJ\x89\x14\n\x06\x12\x04\
    \0\0L\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x02\0\
    \x0e\n\t\n\x02\x03\0\x12\x03\x04\0*\n\x08\n\x01\x08\x12\x03\x06\0?\n\t\n\
    \x02\x08\x0b\x12\x03\x06\0?\nN\n\x01\x07\x12\x04\t\0\x0c\x01\x1aC\x20Thi\
    s\x20extension\x20allows\x20adding\x20options\x20to\x20protocol\x20buffe\
    r\x20messages.\n\nD\n\x02\x07\0\x12\x03\x0b\x024\x1a9\x20Option\x20to\
    \x20specify\x20composite\x20indexes\x20on\x20multiple\x20fields.\n\n\n\n\
    \x03\x07\0\x02\x12\x03\t\x07%\n\n\n\x03\x07\0\x04\x12\x03\x0b\x02\n\n\n\
    \n\x03\x07\0\x06\x12\x03\x0b\x0b!\n\n\n\x03\x07\0\x01\x12\x03\x0b\"+\n\n\
    \n\x03\x07\0\x03\x12\x03\x0b.3\nL\n\x01\x07\x12\x04\x0f\0\x16\x01\x1aA\
    \x20This\x20extension\x20allows\x20adding\x20options\x20to\x20protocol\
    \x20buffer\x20fields.\n\n/\n\x02\x07\x01\x12\x03\x11\x02%\x1a$\x20Option\
    \x20to\x20mark\x20a\x20field\x20as\x20indexed.\n\n\n\n\x03\x07\x01\x02\
    \x12\x03\x0f\x07#\n\n\n\x03\x07\x01\x04\x12\x03\x11\x02\n\n\n\n\x03\x07\
    \x01\x06\x12\x03\x11\x0b\x16\n\n\n\x03\x07\x01\x01\x12\x03\x11\x17\x1c\n\
    \n\n\x03\x07\x01\x03\x12\x03\x11\x1f$\nD\n\x02\x07\x02\x12\x03\x13\x02%\
    \x1a9\x20Option\x20to\x20specify\x20how\x20bytes\x20fields\x20are\x20enc\
    oded/decoded.\n\n\n\n\x03\x07\x02\x02\x12\x03\x0f\x07#\n\n\n\x03\x07\x02\
    \x04\x12\x03\x13\x02\n\n\n\n\x03\x07\x02\x06\x12\x03\x13\x0b\x16\n\n\n\
    \x03\x07\x02\x01\x12\x03\x13\x17\x1c\n\n\n\x03\x07\x02\x03\x12\x03\x13\
    \x1f$\nI\n\x02\x07\x03\x12\x03\x15\x02)\x1a>\x20Option\x20to\x20specify\
    \x20how\x20numeric\x20fields\x20are\x20scaled/represented.\n\n\n\n\x03\
    \x07\x03\x02\x12\x03\x0f\x07#\n\n\n\x03\x07\x03\x04\x12\x03\x15\x02\n\n\
    \n\n\x03\x07\x03\x06\x12\x03\x15\x0b\x18\n\n\n\x03\x07\x03\x01\x12\x03\
    \x15\x19\x20\n\n\n\x03\x07\x03\x03\x12\x03\x15#(\n*\n\x02\x05\0\x12\x04\
    \x19\0\x1e\x01\x1a\x1e\x20Specifies\x20the\x20type\x20of\x20index.\n\n\n\
    \n\x03\x05\0\x01\x12\x03\x19\x05\x0e\n/\n\x04\x05\0\x02\0\x12\x03\x1b\
    \x02\x19\x1a\"\x20Ordered\x20index\x20(maintains\x20order).\n\n\x0c\n\
    \x05\x05\0\x02\0\x01\x12\x03\x1b\x02\x14\n\x0c\n\x05\x05\0\x02\0\x02\x12\
    \x03\x1b\x17\x18\n4\n\x04\x05\0\x02\x01\x12\x03\x1d\x02\x1b\x1a'\x20Unor\
    dered\x20index\x20(faster\x20for\x20lookups).\n\n\x0c\n\x05\x05\0\x02\
    \x01\x01\x12\x03\x1d\x02\x16\n\x0c\n\x05\x05\0\x02\x01\x02\x12\x03\x1d\
    \x19\x1a\n3\n\x02\x04\0\x12\x04!\0&\x01\x1a'\x20Defines\x20options\x20fo\
    r\x20indexing\x20a\x20field.\n\n\n\n\x03\x04\0\x01\x12\x03!\x08\x13\n3\n\
    \x04\x04\0\x02\0\x12\x03#\x02\x15\x1a&\x20Type\x20of\x20index\x20(defaul\
    ts\x20to\x20ordered).\n\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03#\x02\x0b\n\
    \x0c\n\x05\x04\0\x02\0\x01\x12\x03#\x0c\x10\n\x0c\n\x05\x04\0\x02\0\x03\
    \x12\x03#\x13\x14\nB\n\x04\x04\0\x02\x01\x12\x03%\x02\x12\x1a5\x20Whethe\
    r\x20this\x20is\x20a\x20unique\x20index\x20(defaults\x20to\x20false).\n\
    \n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03%\x02\x06\n\x0c\n\x05\x04\0\x02\
    \x01\x01\x12\x03%\x07\r\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03%\x10\x11\n\
    ;\n\x02\x04\x01\x12\x04)\0,\x01\x1a/\x20Defines\x20options\x20for\x20ind\
    exing\x20multiple\x20fields.\n\n\n\n\x03\x04\x01\x01\x12\x03)\x08\x1e\n)\
    \n\x04\x04\x01\x02\0\x12\x03+\x02*\x1a\x1c\x20List\x20of\x20composite\
    \x20indexes.\n\n\x0c\n\x05\x04\x01\x02\0\x04\x12\x03+\x02\n\n\x0c\n\x05\
    \x04\x01\x02\0\x06\x12\x03+\x0b\x1f\n\x0c\n\x05\x04\x01\x02\0\x01\x12\
    \x03+\x20%\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03+()\nN\n\x02\x04\x02\x12\
    \x04/\06\x01\x1aB\x20Defines\x20options\x20for\x20composite\x20indexes\
    \x20involving\x20multiple\x20fields.\n\n\n\n\x03\x04\x02\x01\x12\x03/\
    \x08\x1c\n=\n\x04\x04\x02\x02\0\x12\x031\x02\x15\x1a0\x20Type\x20of\x20c\
    omposite\x20index\x20(defaults\x20to\x20ordered).\n\n\x0c\n\x05\x04\x02\
    \x02\0\x06\x12\x031\x02\x0b\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x031\x0c\
    \x10\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x031\x13\x14\nB\n\x04\x04\x02\x02\
    \x01\x12\x033\x02\x12\x1a5\x20Whether\x20this\x20is\x20a\x20unique\x20in\
    dex\x20(defaults\x20to\x20false).\n\n\x0c\n\x05\x04\x02\x02\x01\x05\x12\
    \x033\x02\x06\n\x0c\n\x05\x04\x02\x02\x01\x01\x12\x033\x07\r\n\x0c\n\x05\
    \x04\x02\x02\x01\x03\x12\x033\x10\x11\nC\n\x04\x04\x02\x02\x02\x12\x035\
    \x02\x1d\x1a6\x20List\x20of\x20field\x20names\x20involved\x20in\x20the\
    \x20composite\x20index.\n\n\x0c\n\x05\x04\x02\x02\x02\x04\x12\x035\x02\n\
    \n\x0c\n\x05\x04\x02\x02\x02\x05\x12\x035\x0b\x11\n\x0c\n\x05\x04\x02\
    \x02\x02\x01\x12\x035\x12\x18\n\x0c\n\x05\x04\x02\x02\x02\x03\x12\x035\
    \x1b\x1c\nD\n\x02\x05\x01\x12\x049\0>\x01\x1a8\x20Specifies\x20the\x20fo\
    rmat\x20for\x20encoding/decoding\x20bytes\x20data.\n\n\n\n\x03\x05\x01\
    \x01\x12\x039\x05\x0f\n(\n\x04\x05\x01\x02\0\x12\x03;\x02\x19\x1a\x1b\
    \x20Standard\x20base64\x20encoding.\n\n\x0c\n\x05\x05\x01\x02\0\x01\x12\
    \x03;\x02\x14\n\x0c\n\x05\x05\x01\x02\0\x02\x12\x03;\x17\x18\n$\n\x04\
    \x05\x01\x02\x01\x12\x03=\x02\x16\x1a\x17\x20Hexadecimal\x20encoding.\n\
    \n\x0c\n\x05\x05\x01\x02\x01\x01\x12\x03=\x02\x11\n\x0c\n\x05\x05\x01\
    \x02\x01\x02\x12\x03=\x14\x15\nG\n\x02\x04\x03\x12\x04A\0D\x01\x1a;\x20D\
    efines\x20options\x20for\x20how\x20bytes\x20fields\x20are\x20encoded/dec\
    oded.\n\n\n\n\x03\x04\x03\x01\x12\x03A\x08\x13\nM\n\x04\x04\x03\x02\0\
    \x12\x03C\x02\x18\x1a@\x20Format\x20to\x20use\x20for\x20displaying\x20bi\
    nary\x20data\x20(defaults\x20to\x20base64).\n\n\x0c\n\x05\x04\x03\x02\0\
    \x06\x12\x03C\x02\x0c\n\x0c\n\x05\x04\x03\x02\0\x01\x12\x03C\r\x13\n\x0c\
    \n\x05\x04\x03\x02\0\x03\x12\x03C\x16\x17\nL\n\x02\x04\x04\x12\x04G\0L\
    \x01\x1a@\x20Defines\x20options\x20for\x20how\x20numeric\x20fields\x20ar\
    e\x20scaled/represented.\n\n\n\n\x03\x04\x04\x01\x12\x03G\x08\x15\nG\n\
    \x04\x04\x04\x02\0\x12\x03I\x02\x20\x1a:\x20Total\x20number\x20of\x20sig\
    nificant\x20digits\x20(including\x20decimals).\n\n\x0c\n\x05\x04\x04\x02\
    \0\x04\x12\x03I\x02\n\n\x0c\n\x05\x04\x04\x02\0\x05\x12\x03I\x0b\x11\n\
    \x0c\n\x05\x04\x04\x02\0\x01\x12\x03I\x12\x1b\n\x0c\n\x05\x04\x04\x02\0\
    \x03\x12\x03I\x1e\x1f\n9\n\x04\x04\x04\x02\x01\x12\x03K\x02\x1c\x1a,\x20\
    Number\x20of\x20decimal\x20places\x20(0\x20for\x20integers).\n\n\x0c\n\
    \x05\x04\x04\x02\x01\x04\x12\x03K\x02\n\n\x0c\n\x05\x04\x04\x02\x01\x05\
    \x12\x03K\x0b\x11\n\x0c\n\x05\x04\x04\x02\x01\x01\x12\x03K\x12\x17\n\x0c\
    \n\x05\x04\x04\x02\x01\x03\x12\x03K\x1a\x1bb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(::protobuf::descriptor::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(5);
            messages.push(IndexOption::generated_message_descriptor_data());
            messages.push(CompositeIndexesOption::generated_message_descriptor_data());
            messages.push(CompositeIndexOption::generated_message_descriptor_data());
            messages.push(BytesOption::generated_message_descriptor_data());
            messages.push(NumericOption::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(2);
            enums.push(IndexType::generated_enum_descriptor_data());
            enums.push(FormatType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
